"""add_guest_fields_to_order

Revision ID: 17a31de78b9d
Revises: 6b91bac880b3
Create Date: 2026-01-26 09:54:05.998477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '17a31de78b9d'
down_revision: Union[str, Sequence[str], None] = '6b91bac880b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('guest_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('guest_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('guest_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('guest_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('order', 'customer_clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'customer_clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('order', 'guest_address')
    op.drop_column('order', 'guest_phone')
    op.drop_column('order', 'guest_email')
    op.drop_column('order', 'guest_name')
    # ### end Alembic commands ###
