"""add_is_approved_to_shop

Revision ID: 6b91bac880b3
Revises: cfc56d2d7454
Create Date: 2026-01-25 20:04:41.493042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b91bac880b3'
down_revision: Union[str, Sequence[str], None] = 'cfc56d2d7454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'is_approved')
    # ### end Alembic commands ###
