"""add_shop_assets

Revision ID: 6bf6f328c80e
Revises: 89d6de9d39f1
Create Date: 2026-01-26 15:57:50.555824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6bf6f328c80e'
down_revision: Union[str, Sequence[str], None] = '89d6de9d39f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('shop', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shop', sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'cover_image_url')
    op.drop_column('shop', 'logo_url')
    op.create_table('user',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    # ### end Alembic commands ###
