"""add_category_system

Revision ID: cc4257691a6f
Revises: 17a31de78b9d
Create Date: 2026-01-26 11:12:08.458258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cc4257691a6f'
down_revision: Union[str, Sequence[str], None] = '17a31de78b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='No description'))
    op.add_column('product', sa.Column('long_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='No description'))
    op.add_column('product', sa.Column('main_category_id', sa.Integer(), nullable=True)) # Make nullable initially
    op.add_column('product', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['main_category_id'], ['id'])
    op.create_foreign_key(None, 'product', 'subcategory', ['sub_category_id'], ['id'])
    # Don't drop description yet to be safe, or just drop it
    op.drop_column('product', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'sub_category_id')
    op.drop_column('product', 'main_category_id')
    op.drop_column('product', 'long_description')
    op.drop_column('product', 'short_description')
    # ### end Alembic commands ###
